/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
/*
 WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

  This file has been sanitized for public viewing.
  It contains the configuration used to connect this app to AWS Cognito for authentication.
  All sensitive values (like client IDs, domains, and pool IDs) have been replaced with placeholders.
  This configuration supports OAuth with Apple and Google as identity providers via Cognito.
*/
const awsmobile = {
    /* Get these from the AWS Amplify console */
    aws_project_region: "YOUR_PROJECT_REGION",
    aws_cognito_identity_pool_id: "YOUR_IDENTITY_POOL_ID",
    aws_cognito_region: "YOUR_COGNITO_REGION",
    aws_user_pools_id: "YOUR_USER_POOL_ID",
    aws_user_pools_web_client_id: "YOUR_WEB_CLIENT_ID",
    oauth: {
        domain: "YOUR_COGNITO_DOMAIN.auth.YOUR_REGION.amazoncognito.com",
        scope: [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        /* Should be the same as the redirect URI in the AWS Amplify console, but with your app scheme */
        redirectSignIn: "yourapp://",
        redirectSignOut: "yourapp://",
        responseType: "code"
    },
    /* Unsure same as in console*/
    federationTarget: "COGNITO_USER_POOLS",
    aws_cognito_username_attributes: [
        "EMAIL"
    ],
    /* Make sure to add the social providers you want to use and configured in the console*/
    aws_cognito_social_providers: [
        "GOOGLE",
        "APPLE"
    ],
    /* Make sure to add the attributes you want to use and configured in the console*/
    aws_cognito_signup_attributes: [
        "EMAIL"
    ],
    aws_cognito_mfa_configuration: "OFF",
    aws_cognito_mfa_types: [
        "SMS"
    ],
    aws_cognito_password_protection_settings: {
        passwordPolicyMinLength: 8,
        passwordPolicyCharacters: []
    },
    aws_cognito_verification_mechanisms: [
        "EMAIL"
    ]
};

export default awsmobile;
